const CFG={symbol:"BTCUSDT",interval:"5m",limit:1000,startingBalance:100,riskPerTrade:8,lookback:10,atrLen:14,volumeLen:20,volumeMult:1.15,displacementATR:1.20,minSLPct:0.0008,maxSLPct:0.0060,bufferATR:0.12,rr:[1,2,3,4]};
const state={candles:[],signal:null,historyExpanded:false};
const $=id=>document.getElementById(id); const fmt=n=>Number(n).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}); const pct=(a,b)=>b?((a-b)/b*100):0;
function setStatus(t,live){$("status").textContent=t;$("status").classList.toggle("live",!!live)}
async function binance(path){const r=await fetch("https://api.binance.com"+path,{cache:"no-store"});if(!r.ok)throw new Error("Binance HTTP "+r.status);return r.json()}
function mapKlines(raw){return raw.map(x=>({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]}))}
function atr(a,n,i){if(i<n)return 0;let s=0;for(let j=i-n+1;j<=i;j++){const p=a[j-1]?a[j-1].c:a[j].o;s+=Math.max(a[j].h-a[j].l,Math.abs(a[j].h-p),Math.abs(a[j].l-p))}return s/n}
function avgVol(a,n,i){let s=0,c=0;for(let j=Math.max(0,i-n);j<i;j++){s+=a[j].v;c++}return c?s/c:0}
function swingHigh(a,i){if(i<2||i+2>=a.length)return false;for(let j=1;j<=2;j++)if(a[i].h<=a[i-j].h||a[i].h<a[i+j].h)return false;return true}
function swingLow(a,i){if(i<2||i+2>=a.length)return false;for(let j=1;j<=2;j++)if(a[i].l>=a[i-j].l||a[i].l>a[i+j].l)return false;return true}
function lastSwing(a,i,type){for(let j=i-2;j>=5;j--){if(type==="high"&&swingHigh(a,j))return j;if(type==="low"&&swingLow(a,j))return j}return -1}
function makeSignal(a,i){const c=a[i],A=atr(a,CFG.atrLen,i),av=avgVol(a,CFG.volumeLen,i);const s={side:null,entry:c.c,sl:null,tps:[],checks:{sweep:false,bos:false,disp:false,volume:false,atr:false,zone:false},reason:[]};if(!A||!av)return s;const prev=a.slice(Math.max(2,i-CFG.lookback),i),hi=Math.max.apply(null,prev.map(x=>x.h)),lo=Math.min.apply(null,prev.map(x=>x.l));const bullSweep=c.l<lo&&c.c>lo,bearSweep=c.h>hi&&c.c<hi;s.checks.sweep=bullSweep||bearSweep;const body=Math.abs(c.c-c.o);s.checks.disp=body>=A*CFG.displacementATR;s.checks.volume=c.v>=av*CFG.volumeMult;const atrPct=A/c.c;s.checks.atr=atrPct>=CFG.minSLPct&&atrPct<=CFG.maxSLPct;const sh=lastSwing(a,i,"high"),sl=lastSwing(a,i,"low");const bullBos=bullSweep&&sh>0&&c.c>a[sh].h,bearBos=bearSweep&&sl>0&&c.c<a[sl].l;s.checks.bos=bullBos||bearBos;const bullFvg=i>=2&&a[i-2].h<c.l,bearFvg=i>=2&&a[i-2].l>c.h,bullOB=i>0&&a[i-1].c<a[i-1].o,bearOB=i>0&&a[i-1].c>a[i-1].o;s.checks.zone=(bullBos&&(bullFvg||bullOB))||(bearBos&&(bearFvg||bearOB));if(!(s.checks.sweep&&s.checks.bos&&s.checks.disp&&s.checks.volume&&s.checks.atr&&s.checks.zone))return s;s.side=bullBos?"BUY":"SELL";s.entry=c.c;let slp=s.side==="BUY"?Math.min(c.l,lo)-A*CFG.bufferATR:Math.max(c.h,hi)+A*CFG.bufferATR;const d=Math.abs(s.entry-slp),minD=s.entry*CFG.minSLPct,maxD=s.entry*CFG.maxSLPct;if(d<minD)slp=s.side==="BUY"?s.entry-minD:s.entry+minD;if(Math.abs(s.entry-slp)>maxD)slp=s.side==="BUY"?s.entry-maxD:s.entry+maxD;s.sl=slp;const risk=Math.abs(s.entry-s.sl);s.tps=CFG.rr.map(r=>s.side==="BUY"?s.entry+r*risk:s.entry-r*risk);s.reason=[s.side==="BUY"?"Sell-side liquidity swept":"Buy-side liquidity swept","Structure break confirmed","Displacement + volume confirmed","OB/FVG confirmation"];return s}
function renderSignal(s){$("signal").className="signal "+(s.side==="BUY"?"buy":s.side==="SELL"?"sell":"neutral");$("signal").textContent=s.side?s.side+" SIGNAL":"NO SIGNAL";$("signalMeta").textContent=s.side?s.reason.join(" · "):"No setup passed all BTC filters on the last confirmed candle.";[["c1","sweep"],["c2","bos"],["c3","disp"],["c4","volume"],["c5","atr"],["c6","zone"]].forEach(x=>$(x[0]).className=s.checks[x[1]]?"ok":"");if(s.side){let h="<div class=\"plan\"><div class=\"level\"><small>Entry</small><b>"+fmt(s.entry)+"</b></div><div class=\"level\"><small>SL</small><b>"+fmt(s.sl)+"</b></div>";s.tps.forEach((x,i)=>h+="<div class=\"level\"><small>TP"+(i+1)+" ("+(i+1)+"R)</small><b>"+fmt(x)+"</b></div>");$("tradePlan").innerHTML=h+"</div>"}else $("tradePlan").textContent="No active setup."}

// XAU-style management:
// - TP1/TP2/TP3 are recorded as hit milestones; the trade stays open.
// - TP2 hit marks the trade as WIN for reporting, but it is not closed.
// - If TP2 was hit and price later reaches SL, report the trade as WIN (+1R), matching the XAU rule.
// - TP4 closes the trade at FULL TP (+4R).
// - If SL is reached before TP2, the trade is LOSS (-1R).
function simulateTrade(a,s,startIndex){let hitTPs=[],result="OPEN",rr=0;for(let j=startIndex+1;j<a.length;j++){const x=a[j];if(s.side==="BUY"){if(x.h>=s.tps[0]&&!hitTPs.includes("TP1"))hitTPs.push("TP1");if(x.h>=s.tps[1]&&!hitTPs.includes("TP2"))hitTPs.push("TP2");if(x.h>=s.tps[2]&&!hitTPs.includes("TP3"))hitTPs.push("TP3");if(x.h>=s.tps[3]){hitTPs.push("TP4");result="FULL TP HIT";rr=4;break}if(x.l<=s.sl){if(hitTPs.includes("TP2")){result="WIN";rr=1}else{result="LOSS";rr=-1}break}}else{if(x.l<=s.tps[0]&&!hitTPs.includes("TP1"))hitTPs.push("TP1");if(x.l<=s.tps[1]&&!hitTPs.includes("TP2"))hitTPs.push("TP2");if(x.l<=s.tps[2]&&!hitTPs.includes("TP3"))hitTPs.push("TP3");if(x.l<=s.tps[3]){hitTPs.push("TP4");result="FULL TP HIT";rr=4;break}if(x.h>=s.sl){if(hitTPs.includes("TP2")){result="WIN";rr=1}else{result="LOSS";rr=-1}break}}}return{result,rr,hitTPs}}
function runBacktest(a){let bal=CFG.startingBalance,wins=0,losses=0,signals=0,rrNet=0,tp2Wins=0,fullWins=0,history=[];for(let i=60;i<a.length-5;i++){const s=makeSignal(a,i);if(!s.side)continue;signals++;const out=simulateTrade(a,s,i);if(out.result==="LOSS"){losses++}else if(out.result==="WIN"){wins++;tp2Wins++}else if(out.result==="FULL TP HIT"){wins++;fullWins++}else continue;rrNet+=out.rr;bal+=out.rr*CFG.riskPerTrade;history.push({side:s.side,entry:s.entry,sl:s.sl,result:out.result,hitTPs:out.hitTPs,rr:out.rr})}$("backtest").innerHTML="<div class=\"row\"><span>Signals tested</span><b>"+signals+"</b></div><div class=\"row\"><span>Closed wins</span><b class=\"green\">"+wins+"</b></div><div class=\"row\"><span>Closed losses</span><b class=\"red\">"+losses+"</b></div><div class=\"row\"><span>TP2 wins</span><b>"+tp2Wins+"</b></div><div class=\"row\"><span>Full TP4 wins</span><b>"+fullWins+"</b></div><div class=\"row\"><span>Net R</span><b>"+rrNet.toFixed(1)+"R</b></div><div class=\"row\"><span>Test balance</span><b>$"+bal.toFixed(2)+"</b></div><small>XAU-style management: TP1–TP3 are tracked while the trade remains open; TP2 qualifies as WIN (+1R), TP4 closes at +4R, and SL before TP2 is -1R. Fees, slippage and same-candle intrabar ordering are not modeled yet.</small>"}}
async function load(){try{setStatus("Loading Binance…");const raw=await binance("/api/v3/klines?symbol="+CFG.symbol+"&interval="+CFG.interval+"&limit="+CFG.limit);state.candles=mapKlines(raw);const last=state.candles[state.candles.length-1],prev=state.candles[state.candles.length-2];$("price").textContent="$"+fmt(last.c);$("change").textContent="Last candle "+pct(last.c,prev.c).toFixed(3)+"%";$("candle").textContent=new Date(last.t).toLocaleTimeString();state.signal=makeSignal(state.candles,state.candles.length-2);renderSignal(state.signal);runBacktest(state.candles);setStatus("Binance LIVE",true)}catch(e){setStatus("Data error");$("signalMeta").textContent=e.message}}
$("reload").onclick=load;$("toggleHistory").onclick=()=>{state.historyExpanded=!state.historyExpanded;$("toggleHistory").textContent=state.historyExpanded?"See less":"See more"};load();setInterval(load,60000);