const CFG={symbol:"BTCUSDT",interval:"5m",limit:1000,startingBalance:100,riskPerTrade:8,lookback:10,atrLen:14,volumeLen:20,volumeMult:1.15,displacementATR:1.20,minSLPct:0.0008,maxSLPct:0.0060,bufferATR:0.12,rr:[1,2,3,4],historyLimit:1000};
const state={candles:[],signal:null,historyExpanded:false,history:[],backtest:null};
const $=id=>document.getElementById(id);
const fmt=n=>Number(n).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=(a,b)=>b?((a-b)/b*100):0;
function setStatus(t,live){$("status").textContent=t;$("status").classList.toggle("live",!!live)}
async function marketKlines(){const sources=[
  async()=>{const r=await fetch("https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=5m&limit=1000",{cache:"no-store"});if(!r.ok)throw new Error("Binance HTTP "+r.status);return {name:"Binance",data:await r.json()};},
  async()=>{const r=await fetch("https://api.bybit.com/v5/market/kline?category=linear&symbol=BTCUSDT&interval=5&limit=1000",{cache:"no-store"});if(!r.ok)throw new Error("Bybit HTTP "+r.status);const j=await r.json();if(j.retCode!==0)throw new Error("Bybit "+j.retMsg);return {name:"Bybit",data:j.result.list.slice().reverse().map(x=>[+x[0],+x[1],+x[2],+x[3],+x[4],+x[5]])};},
  async()=>{const r=await fetch("https://www.okx.com/api/v5/market/candles?instId=BTC-USDT&bar=5m&limit=100",{cache:"no-store"});if(!r.ok)throw new Error("OKX HTTP "+r.status);const j=await r.json();if(j.code!=="0")throw new Error("OKX "+j.msg);return {name:"OKX",data:j.data.slice().reverse().map(x=>[+x[0],+x[1],+x[2],+x[3],+x[4],+x[5]])};}
];let lastError="No market source responded";for(const source of sources){try{return await source()}catch(e){lastError=e?.message||lastError}}throw new Error(lastError)}

function mapKlines(raw){return raw.map(x=>({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]}))}
function atr(a,n,i){if(i<n)return 0;let s=0;for(let j=i-n+1;j<=i;j++){const p=a[j-1]?a[j-1].c:a[j].o;s+=Math.max(a[j].h-a[j].l,Math.abs(a[j].h-p),Math.abs(a[j].l-p))}return s/n}
function avgVol(a,n,i){let s=0,c=0;for(let j=Math.max(0,i-n);j<i;j++){s+=a[j].v;c++}return c?s/c:0}
function swingHigh(a,i){if(i<2||i+2>=a.length)return false;for(let j=1;j<=2;j++)if(a[i].h<=a[i-j].h||a[i].h<a[i+j].h)return false;return true}
function swingLow(a,i){if(i<2||i+2>=a.length)return false;for(let j=1;j<=2;j++)if(a[i].l>=a[i-j].l||a[i].l>a[i+j].l)return false;return true}
function lastSwing(a,i,type){for(let j=i-2;j>=5;j--){if(type==="high"&&swingHigh(a,j))return j;if(type==="low"&&swingLow(a,j))return j}return -1}
function makeSignal(a,i){const c=a[i],A=atr(a,CFG.atrLen,i),av=avgVol(a,CFG.volumeLen,i);const s={side:null,entry:c.c,sl:null,tps:[],checks:{sweep:false,bos:false,disp:false,volume:false,atr:false,zone:false},reason:[]};if(!A||!av)return s;const prev=a.slice(Math.max(2,i-CFG.lookback),i),hi=Math.max.apply(null,prev.map(x=>x.h)),lo=Math.min.apply(null,prev.map(x=>x.l));const bullSweep=c.l<lo&&c.c>lo,bearSweep=c.h>hi&&c.c<hi;s.checks.sweep=bullSweep||bearSweep;const body=Math.abs(c.c-c.o);s.checks.disp=body>=A*CFG.displacementATR;s.checks.volume=c.v>=av*CFG.volumeMult;const atrPct=A/c.c;s.checks.atr=atrPct>=CFG.minSLPct&&atrPct<=CFG.maxSLPct;const sh=lastSwing(a,i,"high"),sl=lastSwing(a,i,"low");const bullBos=bullSweep&&sh>0&&c.c>a[sh].h,bearBos=bearSweep&&sl>0&&c.c<a[sl].l;s.checks.bos=bullBos||bearBos;const bullFvg=i>=2&&a[i-2].h<c.l,bearFvg=i>=2&&a[i-2].l>c.h,bullOB=i>0&&a[i-1].c<a[i-1].o,bearOB=i>0&&a[i-1].c>a[i-1].o;s.checks.zone=(bullBos&&(bullFvg||bullOB))||(bearBos&&(bearFvg||bearOB));if(!(s.checks.sweep&&s.checks.bos&&s.checks.disp&&s.checks.volume&&s.checks.atr&&s.checks.zone))return s;s.side=bullBos?"BUY":"SELL";s.entry=c.c;let slp=s.side==="BUY"?Math.min(c.l,lo)-A*CFG.bufferATR:Math.max(c.h,hi)+A*CFG.bufferATR;const d=Math.abs(s.entry-slp),minD=s.entry*CFG.minSLPct,maxD=s.entry*CFG.maxSLPct;if(d<minD)slp=s.side==="BUY"?s.entry-minD:s.entry+minD;if(Math.abs(s.entry-slp)>maxD)slp=s.side==="BUY"?s.entry-maxD:s.entry+maxD;s.sl=slp;const risk=Math.abs(s.entry-s.sl);s.tps=CFG.rr.map(r=>s.side==="BUY"?s.entry+r*risk:s.entry-r*risk);s.reason=[s.side==="BUY"?"Sell-side liquidity swept":"Buy-side liquidity swept","Structure break confirmed","Displacement + volume confirmed","OB/FVG confirmation"];return s}
function drawChart(){const canvas=$("btcChart");if(!canvas||!state.candles.length)return;const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1,w=Math.max(320,rect.width),h=Math.max(220,rect.height);canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const data=state.candles.slice(-120),pad={l:8,r:58,t:12,b:24},cw=(w-pad.l-pad.r)/data.length;let hi=Math.max(...data.map(x=>x.h)),lo=Math.min(...data.map(x=>x.l));const range=Math.max(hi-lo,1),y=p=>pad.t+(hi-p)/range*(h-pad.t-pad.b);ctx.strokeStyle="rgba(120,160,175,.14)";ctx.lineWidth=1;for(let k=0;k<5;k++){const gy=pad.t+k*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,gy);ctx.lineTo(w-pad.r,gy);ctx.stroke()}ctx.font="10px system-ui";ctx.fillStyle="#78929d";for(let k=0;k<5;k++){const v=hi-k*range/4;ctx.fillText(fmt(v),w-pad.r+7,pad.t+k*(h-pad.t-pad.b)/4+3)}data.forEach((c,i)=>{const x=pad.l+i*cw+cw/2,yo=y(c.o),yc=y(c.c),yh=y(c.h),yl=y(c.l),up=c.c>=c.o;ctx.strokeStyle=up?"#55d89b":"#f07f7f";ctx.fillStyle=up?"#55d89b":"#f07f7f";ctx.beginPath();ctx.moveTo(x,yh);ctx.lineTo(x,yl);ctx.stroke();const body=Math.max(1,Math.abs(yc-yo));ctx.fillRect(x-Math.max(1,cw*.3),Math.min(yo,yc),Math.max(2,cw*.6),body)});const last=data[data.length-1];ctx.strokeStyle="#8bd8ff";ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(pad.l,y(last.c));ctx.lineTo(w-pad.r,y(last.c));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#8bd8ff";ctx.fillText("$"+fmt(last.c),w-pad.r+7,y(last.c)+3);$("chartInfo").textContent="Last "+data.length+" confirmed 5M candles · "+new Date(last.t).toLocaleTimeString()}
window.addEventListener("resize",drawChart);
function renderSignal(s){$("signal").className="signal "+(s.side==="BUY"?"buy":s.side==="SELL"?"sell":"neutral");$("signal").textContent=s.side?s.side+" SIGNAL":"NO SIGNAL";$("signalMeta").textContent=s.side?s.reason.join(" · "):"No setup passed all BTC filters on the last confirmed candle.";[["c1","sweep"],["c2","bos"],["c3","disp"],["c4","volume"],["c5","atr"],["c6","zone"]].forEach(x=>$(x[0]).className=s.checks[x[1]]?"ok":"");if(s.side){let h="<div class=\"plan\"><div class=\"level\"><small>Entry</small><b>"+fmt(s.entry)+"</b></div><div class=\"level\"><small>SL</small><b>"+fmt(s.sl)+"</b></div>";s.tps.forEach((x,i)=>h+="<div class=\"level\"><small>TP"+(i+1)+" ("+(i+1)+"R)</small><b>"+fmt(x)+"</b></div>");$("tradePlan").innerHTML=h+"</div>"}else $("tradePlan").textContent="No active setup."}
function simulateTrade(a,s,startIndex){let hitTPs=[],result="OPEN",rr=0,endIndex=a.length-1;for(let j=startIndex+1;j<a.length;j++){const x=a[j];if(s.side==="BUY"){if(x.h>=s.tps[0]&&!hitTPs.includes("TP1"))hitTPs.push("TP1");if(x.h>=s.tps[1]&&!hitTPs.includes("TP2"))hitTPs.push("TP2");if(x.h>=s.tps[2]&&!hitTPs.includes("TP3"))hitTPs.push("TP3");if(x.h>=s.tps[3]){if(!hitTPs.includes("TP4"))hitTPs.push("TP4");result="FULL TP HIT";rr=4;endIndex=j;break}if(x.l<=s.sl){if(hitTPs.includes("TP2")){result="WIN";rr=1}else{result="LOSS";rr=-1}endIndex=j;break}}else{if(x.l<=s.tps[0]&&!hitTPs.includes("TP1"))hitTPs.push("TP1");if(x.l<=s.tps[1]&&!hitTPs.includes("TP2"))hitTPs.push("TP2");if(x.l<=s.tps[2]&&!hitTPs.includes("TP3"))hitTPs.push("TP3");if(x.l<=s.tps[3]){if(!hitTPs.includes("TP4"))hitTPs.push("TP4");result="FULL TP HIT";rr=4;endIndex=j;break}if(x.h>=s.sl){if(hitTPs.includes("TP2")){result="WIN";rr=1}else{result="LOSS";rr=-1}endIndex=j;break}}}return{result,rr,hitTPs,endIndex}}
function renderHistory(history){const box=$("history");if(!history.length){box.innerHTML="<div class=\"empty\">No BTC signals found in the loaded 5M history.</div>";$("toggleHistory").style.display="none";return}$("toggleHistory").style.display="";const visible=state.historyExpanded?history:history.slice(0,5);let h="<div class=\"history-list\">";visible.forEach((x,n)=>{const sideClass=x.side==="BUY"?"green":"red";const resultClass=x.result==="LOSS"?"red":x.result==="OPEN"?"":"green";const t=new Date(x.time).toLocaleString();const tp=x.hitTPs.length?x.hitTPs.join(", "):"—";h+="<div class=\"history-item\"><div class=\"row\"><span>#"+(n+1)+" · "+t+"</span><b class=\""+sideClass+"\">"+x.side+"</b></div><div class=\"row\"><span>Entry / SL</span><b>"+fmt(x.entry)+" / "+fmt(x.sl)+"</b></div><div class=\"row\"><span>TP hit</span><b>"+tp+"</b></div><div class=\"row\"><span>Result</span><b class=\""+resultClass+"\">"+x.result+(x.result==="OPEN"?"":" · "+(x.rr>0?"+":"")+x.rr+"R")+"</b></div></div>"});h+="</div>";if(!state.historyExpanded&&history.length>5)h+="<small>Showing 5 of "+history.length+" signals. Tap See more to view all loaded history.</small>";box.innerHTML=h;$("toggleHistory").textContent=state.historyExpanded?"See less":"See more"}
function runBacktest(a){let bal=CFG.startingBalance,wins=0,losses=0,signals=0,rrNet=0,tp2Wins=0,fullWins=0;const history=[];for(let i=60;i<a.length-5;i++){const s=makeSignal(a,i);if(!s.side)continue;signals++;const out=simulateTrade(a,s,i);history.push({time:a[i].t,side:s.side,entry:s.entry,sl:s.sl,result:out.result,hitTPs:out.hitTPs,rr:out.rr});if(out.result==="LOSS"){losses++}else if(out.result==="WIN"){wins++;tp2Wins++}else if(out.result==="FULL TP HIT"){wins++;fullWins++}else continue;rrNet+=out.rr;bal+=out.rr*CFG.riskPerTrade}history.sort((a,b)=>b.time-a.time);state.history=history;state.backtest={signals,wins,losses,tp2Wins,fullWins,rrNet,bal};$("balance").textContent="$"+bal.toFixed(2);$("backtest").innerHTML="<div class=\"row\"><span>Signals tested</span><b>"+signals+"</b></div><div class=\"row\"><span>Closed wins</span><b class=\"green\">"+wins+"</b></div><div class=\"row\"><span>Closed losses</span><b class=\"red\">"+losses+"</b></div><div class=\"row\"><span>TP2 wins</span><b>"+tp2Wins+"</b></div><div class=\"row\"><span>Full TP4 wins</span><b>"+fullWins+"</b></div><div class=\"row\"><span>Net R</span><b>"+rrNet.toFixed(1)+"R</b></div><div class=\"row\"><span>Test balance</span><b>$"+bal.toFixed(2)+"</b></div><small>XAU-style management: TP1–TP3 are tracked while the trade remains open; TP2 qualifies as WIN (+1R), TP4 closes at +4R, and SL before TP2 is -1R. Fees, slippage and same-candle intrabar ordering are not modeled yet.</small>";renderHistory(history)}
function runTwoDayAudit(a){const latestClosedIndex=Math.max(60,a.length-2);const cutoff=a[latestClosedIndex].t-(48*60*60*1000);let checked=0,signals=0,buy=0,sell=0;for(let i=60;i<=latestClosedIndex;i++){if(a[i].t<cutoff)continue;checked++;const s=makeSignal(a,i);if(!s.side)continue;signals++;if(s.side==="BUY")buy++;else if(s.side==="SELL")sell++}const hours=Math.max(0,(a[latestClosedIndex].t-cutoff)/3600000);$("twoDayAudit").innerHTML="<div class=\"audit-title\">Last 2 Days · Current 6-filter setup</div><div class=\"row\"><span>Confirmed candles checked</span><b>"+checked+"</b></div><div class=\"row\"><span>Total signals</span><b>"+signals+"</b></div><div class=\"row\"><span>BUY signals</span><b class=\"green\">"+buy+"</b></div><div class=\"row\"><span>SELL signals</span><b class=\"red\">"+sell+"</b></div><small>Exact current logic: Liquidity Sweep + MSS/BOS + Displacement + Volume + ATR + OB/FVG must all pass. Audit window: "+hours.toFixed(0)+" hours ending at the latest confirmed 5M candle. This audit does not change live signal logic.</small>")}
async function load(){try{setStatus("Loading market data…");const source=await marketKlines();state.candles=mapKlines(source.data);if(state.candles.length<70)throw new Error("Not enough Binance 5M candles");const last=state.candles[state.candles.length-1],prev=state.candles[state.candles.length-2];$("price").textContent="$"+fmt(last.c);$("change").textContent="Last candle "+pct(last.c,prev.c).toFixed(3)+"%";$("candle").textContent=new Date(last.t).toLocaleTimeString();state.signal=makeSignal(state.candles,state.candles.length-2);renderSignal(state.signal);runBacktest(state.candles);runTwoDayAudit(state.candles);drawChart();setStatus(source.name+" LIVE",true)}catch(e){setStatus("Data error");$("signalMeta").textContent="Data error: "+e.message;$("chartInfo").textContent="Market data unavailable";console.error(e)}}
$("reload").onclick=load;$("toggleHistory").onclick=()=>{state.historyExpanded=!state.historyExpanded;renderHistory(state.history)};load();setInterval(load,60000);